# Generated by Django 3.0.8 on 2020-07-10 10:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionTier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimumTransaction', models.PositiveIntegerField()),
                ('maximumTransaction', models.PositiveIntegerField()),
                ('probability', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='CheckDiscountLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerID', models.CharField(max_length=256)),
                ('discounted', models.BooleanField()),
                ('transactionAmmount', models.PositiveIntegerField()),
                ('discountedAmmount', models.PositiveIntegerField()),
                ('transactionDateTime', models.DateTimeField()),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.TransactionTier')),
            ],
        ),
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('timeRequest', models.DateTimeField()),
                ('timeResponse', models.DateTimeField()),
                ('elapsedTime', models.DurationField()),
                ('status', models.CharField(max_length=3)),
                ('statusDetails', models.TextField()),
                ('response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.CheckDiscountLog')),
            ],
        ),
    ]
